"""chaned column name status to state

Revision ID: a40545317e24
Revises: 64860c9876a2
Create Date: 2022-06-19 17:05:52.815027

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "a40545317e24"
down_revision = "64860c9876a2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complaints",
        sa.Column(
            "state",
            sa.Enum("pending", "approved", "rejected", name="state"),
            server_default="pending",
            nullable=False,
        ),
    )
    op.drop_column("complaints", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "complaints",
        sa.Column(
            "status",
            postgresql.ENUM("pending", "approved", "rejected", name="state"),
            server_default=sa.text("'pending'::state"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("complaints", "state")
    # ### end Alembic commands ###
