"""added phone column to User

Revision ID: 64860c9876a2
Revises: 3c0784195e46
Create Date: 2022-06-19 16:47:30.256090

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "64860c9876a2"
down_revision = "3c0784195e46"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone")
    # ### end Alembic commands ###
